INFO     root:test_02_usersync.py:146 ==========开始执行用例：usersync_tasks_statistics_01==========
INFO     root:runcase.py:31 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 START-·-·-·-·-·-·-·-·-·-
INFO     root:handleyaml.py:94 Yaml测试用例基础架构检查通过
INFO     root:runcase.py:50 重组后的用例信息：{'name': '查询近7次的同步状态', 'description': '查询近7次的同步状态', 'validate': {'code': 200, 'response': {'statusCode': 0, 'msg': 'success'}}, 'epic': '用户管理', 'feature': '用户同步管理-用户同步', 'story': '查询近几次的同步状态接口', 'base_url': 'https://192.168.148.174:31000', 'request': {'method': 'GET', 'address': '/api/usersync/v1/task/statistics/7', 'headers': {'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6Ijc0Njc3NmJiLWZjZmMtNGMyOC1hMzY3LTY0ODBlNGE5ZmEwMyIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI3NDY3NzZiYi1mY2ZjLTRjMjgtYTM2Ny02NDgwZTRhOWZhMDMiLCJleHAiOjE2ODgwNDI1OTQsImlhdCI6MTY4Nzg2MjU5NH0.O8P51iQijd4dXdw9AlM9NRCQ6SLu28ZirspvKrfBk3eeSCluJZHOpr6MJ7D9V_kPAK1ed1IpQkvahME21OjbVg', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userSync'}}, 'caseid': 'usersync_tasks_statistics_01'}
INFO     root:runcase.py:81 请求地址：https://192.168.148.174:31000/api/usersync/v1/task/statistics/7
INFO     root:runcase.py:82 请求方法：GET
INFO     root:runcase.py:83 请求头：{'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6Ijc0Njc3NmJiLWZjZmMtNGMyOC1hMzY3LTY0ODBlNGE5ZmEwMyIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI3NDY3NzZiYi1mY2ZjLTRjMjgtYTM2Ny02NDgwZTRhOWZhMDMiLCJleHAiOjE2ODgwNDI1OTQsImlhdCI6MTY4Nzg2MjU5NH0.O8P51iQijd4dXdw9AlM9NRCQ6SLu28ZirspvKrfBk3eeSCluJZHOpr6MJ7D9V_kPAK1ed1IpQkvahME21OjbVg', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userSync'}
DEBUG    urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): 192.168.148.174:31000
DEBUG    urllib3.connectionpool:connectionpool.py:456 https://192.168.148.174:31000 "GET /api/usersync/v1/task/statistics/7 HTTP/1.1" 200 705
INFO     root:runcase.py:166 请求接口结果： {'statusCode': 0, 'msg': 'success', 'data': {'status': 'failure', 'statistics': [{'time': '2023-06-27 18:46:16', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 18:46:16', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 18:46:16', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 18:46:16', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 18:46:16', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 18:46:16', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}]}}
INFO     root:checkresult.py:113 code断言通过, 期望状态码:200, 实际状态码:200
INFO     root:checkresult.py:48 返回结果断言通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 0, 'msg': 'success', 'data': {'status': 'failure', 'statistics': [{'time': '2023-06-27 18:46:16', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 18:46:16', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 18:46:16', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 18:46:16', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 18:46:16', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 18:46:16', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}]}}
INFO     root:runcase.py:61 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 END-·-·-·-·-·-·-·-·-·-