INFO     root:test_cases.py:43 ==========执行用例START：config_test==========
INFO     root:runcase.py:42 -·-·-·-·-·-·-·-·-·-执行用例 START：测试数据源配置-·-·-·-·-·-·-·-·-·-
INFO     root:runcase.py:117 -·-·-·-·-·-·-·-·-·-执行接口 START：测试LADP数据源配置成功-·-·-·-·-·-·-·-·-·-
INFO     root:handleyaml.py:84 Yaml测试用例基础架构检查通过
INFO     root:runcase.py:128 重组后的用例信息：{'api_name': '测试数据源配置', 'base_url': 'https://192.168.148.174:31000', 'request': {'method': 'post', 'address': '/api/usersync/v1/config/test', 'headers': {'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6Ijk2NGJiYjI5LWQ5MmUtNGYxMS04NmE2LTliMDMzZmU3MzI1NCIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI5NjRiYmIyOS1kOTJlLTRmMTEtODZhNi05YjAzM2ZlNzMyNTQiLCJleHAiOjE2OTIxODU5MjUsImlhdCI6MTY5MjAwNTkyNX0.QaEUj72R10OUSPFkSrNptyby2e1XoYmTgr3PBkYtFJALpiZ0pxklN7IItaxdKaO2NRYeRvgtzRCmv1wFF1---A', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userSync'}, 'data': {'type': 'domain', 'configs': '{"name":"自动化测试70.235数据源修改","host":"192.168.70.235","port":"389","username":"xiantest\\\\administrator","password":"Ws-123456abcd","base":"DC=xiantest,DC=com","org":"ou=北京明朝万达","isEncrypt":false,"userFilter":"","groupFilter":"","isIncrement":false}'}}, 'name': '测试LADP数据源配置成功', 'description': '填写正确的LDAP数据源配置，点击测试', 'postProcessors': {'assert': {'code': 200, 'response': {'statusCode': 0, 'msg': 'success'}}}}
INFO     root:runcase.py:177 请求地址：https://192.168.148.174:31000/api/usersync/v1/config/test
INFO     root:runcase.py:178 请求方法：post
INFO     root:runcase.py:179 请求头：{'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6Ijk2NGJiYjI5LWQ5MmUtNGYxMS04NmE2LTliMDMzZmU3MzI1NCIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI5NjRiYmIyOS1kOTJlLTRmMTEtODZhNi05YjAzM2ZlNzMyNTQiLCJleHAiOjE2OTIxODU5MjUsImlhdCI6MTY5MjAwNTkyNX0.QaEUj72R10OUSPFkSrNptyby2e1XoYmTgr3PBkYtFJALpiZ0pxklN7IItaxdKaO2NRYeRvgtzRCmv1wFF1---A', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userSync'}
INFO     root:runcase.py:189 请求参数：{'type': 'domain', 'configs': '{"name":"自动化测试70.235数据源修改","host":"192.168.70.235","port":"389","username":"xiantest\\\\administrator","password":"Ws-123456abcd","base":"DC=xiantest,DC=com","org":"ou=北京明朝万达","isEncrypt":false,"userFilter":"","groupFilter":"","isIncrement":false}'}
INFO     root:runcase.py:251 请求接口结果： {'statusCode': 1114402, 'msg': '没有连接权限,账号或密码不正确！'}
INFO     root:checkresult.py:152 code断言通过, 期望状态码:200, 实际状态码:200
ERROR    root:checkresult.py:89 返回结果断言未通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 1114402, 'msg': '没有连接权限,账号或密码不正确！'}
INFO     root:test_cases.py:43 ==========执行用例START：config_test==========
INFO     root:runcase.py:42 -·-·-·-·-·-·-·-·-·-执行用例 START：测试数据源配置-·-·-·-·-·-·-·-·-·-
INFO     root:runcase.py:117 -·-·-·-·-·-·-·-·-·-执行接口 START：测试LADP数据源配置成功-·-·-·-·-·-·-·-·-·-
INFO     root:handleyaml.py:84 Yaml测试用例基础架构检查通过
INFO     root:runcase.py:128 重组后的用例信息：{'api_name': '测试数据源配置', 'base_url': 'https://192.168.148.174:31000', 'request': {'method': 'post', 'address': '/api/usersync/v1/config/test', 'headers': {'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6Ijk2NGJiYjI5LWQ5MmUtNGYxMS04NmE2LTliMDMzZmU3MzI1NCIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI5NjRiYmIyOS1kOTJlLTRmMTEtODZhNi05YjAzM2ZlNzMyNTQiLCJleHAiOjE2OTIxODU5MjUsImlhdCI6MTY5MjAwNTkyNX0.QaEUj72R10OUSPFkSrNptyby2e1XoYmTgr3PBkYtFJALpiZ0pxklN7IItaxdKaO2NRYeRvgtzRCmv1wFF1---A', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userSync'}, 'data': {'type': 'domain', 'configs': '{"name":"自动化测试70.235数据源修改","host":"192.168.70.235","port":"389","username":"xiantest\\\\administrator","password":"Ws-123456abcd","base":"DC=xiantest,DC=com","org":"ou=北京明朝万达","isEncrypt":false,"userFilter":"","groupFilter":"","isIncrement":false}'}}, 'name': '测试LADP数据源配置成功', 'description': '填写正确的LDAP数据源配置，点击测试', 'postProcessors': {'assert': {'code': 200, 'response': {'statusCode': 0, 'msg': 'success'}}}}
INFO     root:runcase.py:177 请求地址：https://192.168.148.174:31000/api/usersync/v1/config/test
INFO     root:runcase.py:178 请求方法：post
INFO     root:runcase.py:179 请求头：{'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6Ijk2NGJiYjI5LWQ5MmUtNGYxMS04NmE2LTliMDMzZmU3MzI1NCIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI5NjRiYmIyOS1kOTJlLTRmMTEtODZhNi05YjAzM2ZlNzMyNTQiLCJleHAiOjE2OTIxODU5MjUsImlhdCI6MTY5MjAwNTkyNX0.QaEUj72R10OUSPFkSrNptyby2e1XoYmTgr3PBkYtFJALpiZ0pxklN7IItaxdKaO2NRYeRvgtzRCmv1wFF1---A', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userSync'}
INFO     root:runcase.py:189 请求参数：{'type': 'domain', 'configs': '{"name":"自动化测试70.235数据源修改","host":"192.168.70.235","port":"389","username":"xiantest\\\\administrator","password":"Ws-123456abcd","base":"DC=xiantest,DC=com","org":"ou=北京明朝万达","isEncrypt":false,"userFilter":"","groupFilter":"","isIncrement":false}'}
INFO     root:runcase.py:251 请求接口结果： {'statusCode': 1114402, 'msg': '没有连接权限,账号或密码不正确！'}
INFO     root:checkresult.py:152 code断言通过, 期望状态码:200, 实际状态码:200
ERROR    root:checkresult.py:89 返回结果断言未通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 1114402, 'msg': '没有连接权限,账号或密码不正确！'}
INFO     root:test_cases.py:43 ==========执行用例START：config_test==========
INFO     root:runcase.py:42 -·-·-·-·-·-·-·-·-·-执行用例 START：测试数据源配置-·-·-·-·-·-·-·-·-·-
INFO     root:runcase.py:117 -·-·-·-·-·-·-·-·-·-执行接口 START：测试LADP数据源配置成功-·-·-·-·-·-·-·-·-·-
INFO     root:handleyaml.py:84 Yaml测试用例基础架构检查通过
INFO     root:runcase.py:128 重组后的用例信息：{'api_name': '测试数据源配置', 'base_url': 'https://192.168.148.174:31000', 'request': {'method': 'post', 'address': '/api/usersync/v1/config/test', 'headers': {'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6Ijk2NGJiYjI5LWQ5MmUtNGYxMS04NmE2LTliMDMzZmU3MzI1NCIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI5NjRiYmIyOS1kOTJlLTRmMTEtODZhNi05YjAzM2ZlNzMyNTQiLCJleHAiOjE2OTIxODU5MjUsImlhdCI6MTY5MjAwNTkyNX0.QaEUj72R10OUSPFkSrNptyby2e1XoYmTgr3PBkYtFJALpiZ0pxklN7IItaxdKaO2NRYeRvgtzRCmv1wFF1---A', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userSync'}, 'data': {'type': 'domain', 'configs': '{"name":"自动化测试70.235数据源修改","host":"192.168.70.235","port":"389","username":"xiantest\\\\administrator","password":"Ws-123456abcd","base":"DC=xiantest,DC=com","org":"ou=北京明朝万达","isEncrypt":false,"userFilter":"","groupFilter":"","isIncrement":false}'}}, 'name': '测试LADP数据源配置成功', 'description': '填写正确的LDAP数据源配置，点击测试', 'postProcessors': {'assert': {'code': 200, 'response': {'statusCode': 0, 'msg': 'success'}}}}
INFO     root:runcase.py:177 请求地址：https://192.168.148.174:31000/api/usersync/v1/config/test
INFO     root:runcase.py:178 请求方法：post
INFO     root:runcase.py:179 请求头：{'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6Ijk2NGJiYjI5LWQ5MmUtNGYxMS04NmE2LTliMDMzZmU3MzI1NCIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI5NjRiYmIyOS1kOTJlLTRmMTEtODZhNi05YjAzM2ZlNzMyNTQiLCJleHAiOjE2OTIxODU5MjUsImlhdCI6MTY5MjAwNTkyNX0.QaEUj72R10OUSPFkSrNptyby2e1XoYmTgr3PBkYtFJALpiZ0pxklN7IItaxdKaO2NRYeRvgtzRCmv1wFF1---A', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userSync'}
INFO     root:runcase.py:189 请求参数：{'type': 'domain', 'configs': '{"name":"自动化测试70.235数据源修改","host":"192.168.70.235","port":"389","username":"xiantest\\\\administrator","password":"Ws-123456abcd","base":"DC=xiantest,DC=com","org":"ou=北京明朝万达","isEncrypt":false,"userFilter":"","groupFilter":"","isIncrement":false}'}
INFO     root:runcase.py:251 请求接口结果： {'statusCode': 1114402, 'msg': '没有连接权限,账号或密码不正确！'}
INFO     root:checkresult.py:152 code断言通过, 期望状态码:200, 实际状态码:200
ERROR    root:checkresult.py:89 返回结果断言未通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 1114402, 'msg': '没有连接权限,账号或密码不正确！'}
INFO     root:test_cases.py:43 ==========执行用例START：config_test==========
INFO     root:runcase.py:42 -·-·-·-·-·-·-·-·-·-执行用例 START：测试数据源配置-·-·-·-·-·-·-·-·-·-
INFO     root:runcase.py:117 -·-·-·-·-·-·-·-·-·-执行接口 START：测试LADP数据源配置成功-·-·-·-·-·-·-·-·-·-
INFO     root:handleyaml.py:84 Yaml测试用例基础架构检查通过
INFO     root:runcase.py:128 重组后的用例信息：{'api_name': '测试数据源配置', 'base_url': 'https://192.168.148.174:31000', 'request': {'method': 'post', 'address': '/api/usersync/v1/config/test', 'headers': {'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6Ijk2NGJiYjI5LWQ5MmUtNGYxMS04NmE2LTliMDMzZmU3MzI1NCIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI5NjRiYmIyOS1kOTJlLTRmMTEtODZhNi05YjAzM2ZlNzMyNTQiLCJleHAiOjE2OTIxODU5MjUsImlhdCI6MTY5MjAwNTkyNX0.QaEUj72R10OUSPFkSrNptyby2e1XoYmTgr3PBkYtFJALpiZ0pxklN7IItaxdKaO2NRYeRvgtzRCmv1wFF1---A', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userSync'}, 'data': {'type': 'domain', 'configs': '{"name":"自动化测试70.235数据源修改","host":"192.168.70.235","port":"389","username":"xiantest\\\\administrator","password":"Ws-123456abcd","base":"DC=xiantest,DC=com","org":"ou=北京明朝万达","isEncrypt":false,"userFilter":"","groupFilter":"","isIncrement":false}'}}, 'name': '测试LADP数据源配置成功', 'description': '填写正确的LDAP数据源配置，点击测试', 'postProcessors': {'assert': {'code': 200, 'response': {'statusCode': 0, 'msg': 'success'}}}}
INFO     root:runcase.py:177 请求地址：https://192.168.148.174:31000/api/usersync/v1/config/test
INFO     root:runcase.py:178 请求方法：post
INFO     root:runcase.py:179 请求头：{'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6Ijk2NGJiYjI5LWQ5MmUtNGYxMS04NmE2LTliMDMzZmU3MzI1NCIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI5NjRiYmIyOS1kOTJlLTRmMTEtODZhNi05YjAzM2ZlNzMyNTQiLCJleHAiOjE2OTIxODU5MjUsImlhdCI6MTY5MjAwNTkyNX0.QaEUj72R10OUSPFkSrNptyby2e1XoYmTgr3PBkYtFJALpiZ0pxklN7IItaxdKaO2NRYeRvgtzRCmv1wFF1---A', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userSync'}
INFO     root:runcase.py:189 请求参数：{'type': 'domain', 'configs': '{"name":"自动化测试70.235数据源修改","host":"192.168.70.235","port":"389","username":"xiantest\\\\administrator","password":"Ws-123456abcd","base":"DC=xiantest,DC=com","org":"ou=北京明朝万达","isEncrypt":false,"userFilter":"","groupFilter":"","isIncrement":false}'}
INFO     root:runcase.py:251 请求接口结果： {'statusCode': 1114402, 'msg': '没有连接权限,账号或密码不正确！'}
INFO     root:checkresult.py:152 code断言通过, 期望状态码:200, 实际状态码:200
ERROR    root:checkresult.py:89 返回结果断言未通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 1114402, 'msg': '没有连接权限,账号或密码不正确！'}