INFO     root:test_03_syncManage.py:37 ==========开始执行用例：usersyncManage_push_01==========
INFO     root:runcase.py:29 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 START-·-·-·-·-·-·-·-·-·-
INFO     root:handleyaml.py:94 Yaml测试用例基础架构检查通过
INFO     root:runcase.py:29 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 START-·-·-·-·-·-·-·-·-·-
INFO     root:handleyaml.py:94 Yaml测试用例基础架构检查通过
INFO     root:runcase.py:45 重组后的用例信息：{'name': '同步用户列表状态查询', 'description': '同步用户列表状态查询', 'request': {'data': {'page': 1, 'rows': 20}, 'method': 'GET', 'address': '/api/user/v1/syncManage/list', 'headers': {'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6IjI3MTM3NmQzLTBiZDktNDQ0Ni05ZGU5LThlMDZmM2YwM2Q4ZCIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiIyNzEzNzZkMy0wYmQ5LTQ0NDYtOWRlOS04ZTA2ZjNmMDNkOGQiLCJleHAiOjE2ODcxOTM3MzMsImlhdCI6MTY4NzAxMzczM30.Biu_6v1RwD72vA1X9gTejk7wW0bRoGbthwJGX28Y0XqDcwnzZ5VxENlK6o8nogaP5oEhcuhUrITOGgpvz2gh6w', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userPush'}}, 'validate': {'code': 200, 'response': {'statusCode': 0, 'msg': 'success'}}, 'epic': '用户管理', 'feature': '用户同步管理-用户推送', 'story': '同步用户列表状态查询接口', 'base_url': 'https://192.168.148.174:31000', 'caseid': 'usersyncManage_list_01'}
INFO     root:runcase.py:81 请求地址：https://192.168.148.174:31000/api/user/v1/syncManage/list
INFO     root:runcase.py:82 请求方法：GET
INFO     root:runcase.py:83 请求头：{'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6IjI3MTM3NmQzLTBiZDktNDQ0Ni05ZGU5LThlMDZmM2YwM2Q4ZCIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiIyNzEzNzZkMy0wYmQ5LTQ0NDYtOWRlOS04ZTA2ZjNmMDNkOGQiLCJleHAiOjE2ODcxOTM3MzMsImlhdCI6MTY4NzAxMzczM30.Biu_6v1RwD72vA1X9gTejk7wW0bRoGbthwJGX28Y0XqDcwnzZ5VxENlK6o8nogaP5oEhcuhUrITOGgpvz2gh6w', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userPush'}
INFO     root:runcase.py:93 请求参数：{'page': 1, 'rows': 20}
DEBUG    urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): 192.168.148.174:31000
DEBUG    urllib3.connectionpool:connectionpool.py:456 https://192.168.148.174:31000 "GET /api/user/v1/syncManage/list?page=1&rows=20 HTTP/1.1" 200 688
INFO     root:runcase.py:158 请求接口结果： {'statusCode': 0, 'msg': 'success', 'data': {'totalCount': 3, 'list': [{'privateTopic': 'sync-private-1', 'systemName': '接入系统-1', 'syncGroupStatus': '72/72', 'syncUserStatus': '2356/2357', 'syncGroupCustomStatus': None, 'lastPushTime': '2023-06-16 17:16:46', 'syncStatus': 1}, {'privateTopic': 'sync-private-approve002', 'systemName': '自定义审批系统', 'syncGroupStatus': '3/3', 'syncUserStatus': '2/2', 'syncGroupCustomStatus': None, 'lastPushTime': '2023-06-08 18:38:03', 'syncStatus': 1}, {'privateTopic': 'sync-private-business002', 'systemName': '集中监控与审计系统', 'syncGroupStatus': '3/3', 'syncUserStatus': '2/2', 'syncGroupCustomStatus': None, 'lastPushTime': '2023-06-08 18:37:56', 'syncStatus': 1}]}}
INFO     root:checkresult.py:111 code断言通过, 期望状态码:200, 实际状态码:200
INFO     root:checkresult.py:46 返回结果断言通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 0, 'msg': 'success', 'data': {'totalCount': 3, 'list': [{'privateTopic': 'sync-private-1', 'systemName': '接入系统-1', 'syncGroupStatus': '72/72', 'syncUserStatus': '2356/2357', 'syncGroupCustomStatus': None, 'lastPushTime': '2023-06-16 17:16:46', 'syncStatus': 1}, {'privateTopic': 'sync-private-approve002', 'systemName': '自定义审批系统', 'syncGroupStatus': '3/3', 'syncUserStatus': '2/2', 'syncGroupCustomStatus': None, 'lastPushTime': '2023-06-08 18:38:03', 'syncStatus': 1}, {'privateTopic': 'sync-private-business002', 'systemName': '集中监控与审计系统', 'syncGroupStatus': '3/3', 'syncUserStatus': '2/2', 'syncGroupCustomStatus': None, 'lastPushTime': '2023-06-08 18:37:56', 'syncStatus': 1}]}}
INFO     root:runcase.py:61 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 END-·-·-·-·-·-·-·-·-·-
INFO     root:runcase.py:45 重组后的用例信息：{'name': '用户推送', 'description': '用户推送', 'relevance': [{'caseid': 'usersyncManage_list_01', 'response': [{'value': '$.data.list[0].privateTopic', 'name': 'privateTopic'}]}], 'validate': {'code': 200, 'response': {'statusCode': 0, 'msg': 'success'}}, 'epic': '用户管理', 'feature': '用户同步管理-用户推送', 'story': '用户推送接口', 'base_url': 'https://192.168.148.174:31000', 'request': {'method': 'PUT', 'address': '/api/user/v1/syncManage/push/sync-private-1', 'headers': {'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6IjI3MTM3NmQzLTBiZDktNDQ0Ni05ZGU5LThlMDZmM2YwM2Q4ZCIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiIyNzEzNzZkMy0wYmQ5LTQ0NDYtOWRlOS04ZTA2ZjNmMDNkOGQiLCJleHAiOjE2ODcxOTM3MzMsImlhdCI6MTY4NzAxMzczM30.Biu_6v1RwD72vA1X9gTejk7wW0bRoGbthwJGX28Y0XqDcwnzZ5VxENlK6o8nogaP5oEhcuhUrITOGgpvz2gh6w', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userPush'}}, 'caseid': 'usersyncManage_push_01'}
INFO     root:runcase.py:81 请求地址：https://192.168.148.174:31000/api/user/v1/syncManage/push/sync-private-1
INFO     root:runcase.py:82 请求方法：PUT
INFO     root:runcase.py:83 请求头：{'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6IjI3MTM3NmQzLTBiZDktNDQ0Ni05ZGU5LThlMDZmM2YwM2Q4ZCIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiIyNzEzNzZkMy0wYmQ5LTQ0NDYtOWRlOS04ZTA2ZjNmMDNkOGQiLCJleHAiOjE2ODcxOTM3MzMsImlhdCI6MTY4NzAxMzczM30.Biu_6v1RwD72vA1X9gTejk7wW0bRoGbthwJGX28Y0XqDcwnzZ5VxENlK6o8nogaP5oEhcuhUrITOGgpvz2gh6w', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userPush'}
DEBUG    urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): 192.168.148.174:31000
DEBUG    urllib3.connectionpool:connectionpool.py:456 https://192.168.148.174:31000 "PUT /api/user/v1/syncManage/push/sync-private-1 HTTP/1.1" 200 32
INFO     root:runcase.py:175 请求接口结果： {'statusCode': 0, 'msg': 'success'}
INFO     root:checkresult.py:111 code断言通过, 期望状态码:200, 实际状态码:200
INFO     root:checkresult.py:46 返回结果断言通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 0, 'msg': 'success'}
INFO     root:runcase.py:61 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 END-·-·-·-·-·-·-·-·-·-