ERROR[2023-08-17 15:17:54,647][17016][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': -1}, 实际返回值:{'statusCode': 0}
ERROR[2023-08-17 15:18:00,274][17016][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': -1}, 实际返回值:{'statusCode': 0}
ERROR[2023-08-17 15:18:05,619][17016][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': -1}, 实际返回值:{'statusCode': 0}
ERROR[2023-08-17 15:18:10,993][17016][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': -1}, 实际返回值:{'statusCode': 0}
ERROR[2023-08-17 15:18:11,119][17016][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': -1}, 实际返回值:{'statusCode': 0}
ERROR[2023-08-17 15:18:16,290][17016][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': -1}, 实际返回值:{'statusCode': 0}
ERROR[2023-08-17 15:18:21,463][17016][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': -1}, 实际返回值:{'statusCode': 0}
ERROR[2023-08-17 15:18:26,663][17016][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': -1}, 实际返回值:{'statusCode': 0}
ERROR[2023-08-17 15:18:32,770][17016][checkresult.py checkresult assert_db 63]：数据库断言未通过, 期望返回值:0, 实际返回值：1
ERROR[2023-08-17 15:18:37,903][17016][checkresult.py checkresult assert_db 63]：数据库断言未通过, 期望返回值:0, 实际返回值：1
ERROR[2023-08-17 15:18:43,071][17016][checkresult.py checkresult assert_db 63]：数据库断言未通过, 期望返回值:0, 实际返回值：1
ERROR[2023-08-17 15:18:48,270][17016][checkresult.py checkresult assert_db 63]：数据库断言未通过, 期望返回值:0, 实际返回值：1
ERROR[2023-08-17 15:18:48,450][17016][checkresult.py checkresult assert_db 63]：数据库断言未通过, 期望返回值:0, 实际返回值：1
ERROR[2023-08-17 15:18:53,630][17016][checkresult.py checkresult assert_db 63]：数据库断言未通过, 期望返回值:0, 实际返回值：1
ERROR[2023-08-17 15:18:58,791][17016][checkresult.py checkresult assert_db 63]：数据库断言未通过, 期望返回值:0, 实际返回值：1
ERROR[2023-08-17 15:19:03,908][17016][checkresult.py checkresult assert_db 63]：数据库断言未通过, 期望返回值:0, 实际返回值：1
ERROR[2023-08-17 15:19:21,114][17016][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 1114402, 'msg': '没有连接权限,账号或密码不正确！'}
ERROR[2023-08-17 15:19:26,297][17016][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 1114402, 'msg': '没有连接权限,账号或密码不正确！'}
ERROR[2023-08-17 15:19:31,473][17016][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 1114402, 'msg': '没有连接权限,账号或密码不正确！'}
ERROR[2023-08-17 15:19:36,706][17016][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 1114402, 'msg': '没有连接权限,账号或密码不正确！'}
ERROR[2023-08-17 15:19:42,075][17016][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 1114885, 'msg': '该批次用户已经被覆盖，无法编辑'}
ERROR[2023-08-17 15:19:47,821][17016][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 1114885, 'msg': '该批次用户已经被覆盖，无法编辑'}
ERROR[2023-08-17 15:19:53,512][17016][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 1114885, 'msg': '该批次用户已经被覆盖，无法编辑'}
ERROR[2023-08-17 15:19:59,236][17016][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 1114885, 'msg': '该批次用户已经被覆盖，无法编辑'}
