ERROR[2023-08-07 14:31:03,954][16044][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': -1}, 实际返回值:{'statusCode': 0}
ERROR[2023-08-07 14:31:09,707][16044][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': -1}, 实际返回值:{'statusCode': 0}
ERROR[2023-08-07 14:31:15,089][16044][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': -1}, 实际返回值:{'statusCode': 0}
ERROR[2023-08-07 14:31:20,469][16044][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': -1}, 实际返回值:{'statusCode': 0}
ERROR[2023-08-07 14:31:20,596][16044][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': -1}, 实际返回值:{'statusCode': 0}
ERROR[2023-08-07 14:31:25,802][16044][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': -1}, 实际返回值:{'statusCode': 0}
ERROR[2023-08-07 14:31:31,016][16044][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': -1}, 实际返回值:{'statusCode': 0}
ERROR[2023-08-07 14:31:36,175][16044][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': -1}, 实际返回值:{'statusCode': 0}
ERROR[2023-08-07 14:31:43,465][16044][checkresult.py checkresult assert_db 63]：数据库断言未通过, 期望返回值:0, 实际返回值：1
ERROR[2023-08-07 14:31:48,662][16044][checkresult.py checkresult assert_db 63]：数据库断言未通过, 期望返回值:0, 实际返回值：1
ERROR[2023-08-07 14:31:53,822][16044][checkresult.py checkresult assert_db 63]：数据库断言未通过, 期望返回值:0, 实际返回值：1
ERROR[2023-08-07 14:31:59,026][16044][checkresult.py checkresult assert_db 63]：数据库断言未通过, 期望返回值:0, 实际返回值：1
ERROR[2023-08-07 14:31:59,185][16044][checkresult.py checkresult assert_db 63]：数据库断言未通过, 期望返回值:0, 实际返回值：1
ERROR[2023-08-07 14:32:04,329][16044][checkresult.py checkresult assert_db 63]：数据库断言未通过, 期望返回值:0, 实际返回值：1
ERROR[2023-08-07 14:32:09,576][16044][checkresult.py checkresult assert_db 63]：数据库断言未通过, 期望返回值:0, 实际返回值：1
ERROR[2023-08-07 14:32:14,785][16044][checkresult.py checkresult assert_db 63]：数据库断言未通过, 期望返回值:0, 实际返回值：1
ERROR[2023-08-07 14:34:41,379][16044][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 1114404, 'msg': '无法连接,地址或端口不正确！'}
ERROR[2023-08-07 14:34:52,800][16044][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 1114886, 'msg': '找不到对应的组织机构'}
ERROR[2023-08-07 14:34:59,101][16044][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 1114886, 'msg': '找不到对应的组织机构'}
ERROR[2023-08-07 14:35:05,443][16044][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 1114886, 'msg': '找不到对应的组织机构'}
ERROR[2023-08-07 14:35:13,321][16044][checkresult.py checkresult assert_response 89]：返回结果断言未通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 1114886, 'msg': '找不到对应的组织机构'}
