INFO     root:test_02_usersync.py:146 ==========开始执行用例：usersync_tasks_statistics_01==========
INFO     root:runcase.py:30 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 START-·-·-·-·-·-·-·-·-·-
INFO     root:handleyaml.py:94 Yaml测试用例基础架构检查通过
INFO     root:runcase.py:47 重组后的用例信息：{'name': '查询近7次的同步状态', 'description': '查询近7次的同步状态', 'validate': {'code': 200, 'response': {'statusCode': 0, 'msg': 'success'}}, 'epic': '用户管理', 'feature': '用户同步管理-用户同步', 'story': '查询近几次的同步状态接口', 'base_url': 'https://192.168.148.174:31000', 'request': {'method': 'GET', 'address': '/api/usersync/v1/task/statistics/7', 'headers': {'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6IjY1OTBhNTE1LTA0Y2EtNDA5ZS1hNzBmLWMxZDk2MDY1MTU5MiIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI2NTkwYTUxNS0wNGNhLTQwOWUtYTcwZi1jMWQ5NjA2NTE1OTIiLCJleHAiOjE2ODgwMzE2MjMsImlhdCI6MTY4Nzg1MTYyM30.ZQ97PBbwO0FxfTBcZAH7cNMO0z8M0fncEgMdMVNutTK5fS6qwMFhZur757v9anwBP_z2errE-UoAcB88J2n1ag', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userSync'}}, 'caseid': 'usersync_tasks_statistics_01'}
INFO     root:runcase.py:83 请求地址：https://192.168.148.174:31000/api/usersync/v1/task/statistics/7
INFO     root:runcase.py:84 请求方法：GET
INFO     root:runcase.py:85 请求头：{'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6IjY1OTBhNTE1LTA0Y2EtNDA5ZS1hNzBmLWMxZDk2MDY1MTU5MiIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI2NTkwYTUxNS0wNGNhLTQwOWUtYTcwZi1jMWQ5NjA2NTE1OTIiLCJleHAiOjE2ODgwMzE2MjMsImlhdCI6MTY4Nzg1MTYyM30.ZQ97PBbwO0FxfTBcZAH7cNMO0z8M0fncEgMdMVNutTK5fS6qwMFhZur757v9anwBP_z2errE-UoAcB88J2n1ag', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userSync'}
DEBUG    urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): 192.168.148.174:31000
DEBUG    urllib3.connectionpool:connectionpool.py:456 https://192.168.148.174:31000 "GET /api/usersync/v1/task/statistics/7 HTTP/1.1" 200 705
INFO     root:runcase.py:168 请求接口结果： {'statusCode': 0, 'msg': 'success', 'data': {'status': 'failure', 'statistics': [{'time': '2023-06-27 15:43:26', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 15:43:26', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 15:43:26', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 15:43:26', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 15:43:26', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 15:43:26', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}]}}
INFO     root:checkresult.py:113 code断言通过, 期望状态码:200, 实际状态码:200
INFO     root:checkresult.py:48 返回结果断言通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 0, 'msg': 'success', 'data': {'status': 'failure', 'statistics': [{'time': '2023-06-27 15:43:26', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 15:43:26', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 15:43:26', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 15:43:26', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 15:43:26', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}, {'time': '2023-06-27 15:43:26', 'usergroupSuccCnt': 0, 'userSuccCnt': 0, 'usergroupFailCnt': 0, 'userFailCnt': 0}]}}
INFO     root:runcase.py:63 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 END-·-·-·-·-·-·-·-·-·-