{"name": "测试数据源配置", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <test_cases.TestUserSync object at 0x000001D680B3D190>\ncase = 'config_test'\ncasedata = {'description': '测试数据源配置', 'epic': '用户管理', 'feature': '用户同步管理', 'name': '测试数据源配置', ...}\n\n    @pytest.mark.parametrize('case, casedata', readcase.ReadCase().get_case(businesscase_pathlist))\n    def test_businesscases(self, case, casedata):\n        handleallure.allure_display(casedata)\n        logging.info(\"==========执行用例START：%s==========\", case)\n>       runcase.RunCase().excute_case(casedata)\n\ntestcases\\test_cases.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncommon\\runcase.py:59: in excute_case\n    self.excute_apicase(api, api_casedata)\ncommon\\runcase.py:90: in excute_apicase\n    checkresult.check_result(hope_result, recv_data, recv_code)\ncommon\\checkresult.py:31: in check_result\n    assert_response(value, real_res)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nhope_res = {'msg': 'success', 'statusCode': 0}\nreal_res = {'msg': '无法连接,地址或端口不正确！', 'statusCode': 1114404}\n\n    def assert_response(hope_res, real_res):\n        \"\"\"\n        返回结果校验 -全返回校验\n        :param hope_res:\n        :param real_res:\n        :return:\n        \"\"\"\n        try:\n            with allure.step(\"返回值校验\"):\n                allure.attach(name=\"期望返回值\", body=str(hope_res))\n                allure.attach(name='实际返回值', body=str(real_res))\n                if isinstance(hope_res, (dict, list)) and isinstance(real_res, (dict, list)):\n                    flag = handledict.cmp_dict(hope_res, real_res)\n>                   assert flag\nE                   AssertionError\n\ncommon\\checkresult.py:84: AssertionError"}, "description": "测试数据源配置", "steps": [{"name": "测试LADP数据源配置成功", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"E:\\Wondersoft_ApiTest\\common\\runcase.py\", line 59, in excute_case\n    self.excute_apicase(api, api_casedata)\n  File \"E:\\Wondersoft_ApiTest\\common\\runcase.py\", line 90, in excute_apicase\n    checkresult.check_result(hope_result, recv_data, recv_code)\n  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 31, in check_result\n    assert_response(value, real_res)\n  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 84, in assert_response\n    assert flag\n"}, "steps": [{"name": "发送请求", "status": "passed", "attachments": [{"name": "请求方法：", "source": "0e850673-847c-4095-9207-933726391ef5-attachment.attach"}, {"name": "请求地址", "source": "1c981727-6e64-457b-af36-b49a25755acb-attachment.attach"}, {"name": "请求头", "source": "07d1ae74-ddf7-43bb-9513-8a77e0fdb8af-attachment.attach"}, {"name": "请求参数", "source": "2f6e097d-299a-4637-a5f4-30aa6947adf5-attachment.attach"}, {"name": "请求结果", "source": "c349f95c-dfbe-4288-8c8f-ec2b312fa4b6-attachment.attach"}], "start": 1691389950987, "stop": 1691390081364}, {"name": "结果校验", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 31, in check_result\n    assert_response(value, real_res)\n  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 84, in assert_response\n    assert flag\n"}, "steps": [{"name": "状态码校验", "status": "passed", "attachments": [{"name": "期望状态码", "source": "d8d695a3-4279-4049-961a-9613fa10ed06-attachment.attach"}, {"name": "实际状态码", "source": "ef59e17d-3afd-4529-bfa2-7f7fb5ec034b-attachment.attach"}], "start": 1691390081364, "stop": 1691390081365}, {"name": "返回值校验", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 84, in assert_response\n    assert flag\n"}, "attachments": [{"name": "期望返回值", "source": "5ec28eec-09b1-4f62-aa33-477add5374bd-attachment.attach"}, {"name": "实际返回值", "source": "ce41c60a-0c26-45dd-b927-5523b27db234-attachment.attach"}], "start": 1691390081365, "stop": 1691390081380}], "start": 1691390081364, "stop": 1691390081381}], "start": 1691389950986, "stop": 1691390081381}], "attachments": [{"name": "log", "source": "f27b15d7-4b70-4483-8d7d-92ef346b396f-attachment.txt", "type": "text/plain"}], "start": 1691389950975, "stop": 1691390081381, "uuid": "458bc370-ac0b-45ce-90e9-83750c0dd836", "historyId": "f25bd64294e77074dd8fcf15a47c34e2", "testCaseId": "2cc05bdd47264d0a6d036e2b95402968", "fullName": "testcases.test_cases.TestUserSync#test_businesscases", "labels": [{"name": "epic", "value": "用户管理"}, {"name": "feature", "value": "用户同步管理"}, {"name": "story", "value": "用户同步"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_cases"}, {"name": "subSuite", "value": "TestUserSync"}, {"name": "host", "value": "OFYI7JX9DURTDV6"}, {"name": "thread", "value": "20992-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_cases"}]}