{"name": "获取同步根组id", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <bms.testcases.test_02_usersync.TestUserSync object at 0x000002197C3CB910>\ncaseid = 'usersync_get_syncgroupid_01'\ncasedata = {'base_url': '${config(host)}', 'caseid': 'usersync_get_syncgroupid_01', 'description': '获取同步根组id', 'epic': '用户管理', ...}\n\n    @pytest.mark.parametrize('caseid, casedata', [(caseid, casedata) for caseid, casedata in\n                                                  readcase.ReadCase().get_case_dict(\n                                                      ROOT_DIR + 'bms/data/usersync/usersync_get_syncgroupid.yaml').items()])\n    def test_usersync_get_syncgroupid(self, caseid, casedata):\n        handleallure.allure_display(casedata)\n        logging.info(\"==========开始执行用例：%s==========\", caseid)\n>       runcase.excute_case(casedata)\n\nbms\\testcases\\test_02_usersync.py:165: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncommon\\runcase.py:54: in excute_case\n    checkresult.check_result(hope_result, recv_data, recv_code)\ncommon\\checkresult.py:30: in check_result\n    assert_response(value, real_res)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nhope_res = {'msg': 'success', 'statusCode': 0}\nreal_res = {'msg': '找不到对应的组织机构', 'statusCode': 1114886}\n\n    def assert_response(hope_res, real_res):\n        \"\"\"\n        返回结果校验 -全返回校验\n        :param hope_res:\n        :param real_res:\n        :return:\n        \"\"\"\n        try:\n            with allure.step(\"返回值校验\"):\n                allure.attach(name=\"期望返回值\", body=str(hope_res))\n                allure.attach(name='实际返回值', body=str(real_res))\n                if isinstance(hope_res, dict) and isinstance(real_res, dict):\n                    flag = handledict.cmp_dict(hope_res, real_res)\n>                   assert flag\nE                   AssertionError\n\ncommon\\checkresult.py:45: AssertionError"}, "description": "获取同步根组id", "steps": [{"name": "执行关联接口", "status": "passed", "steps": [{"name": "执行当前接口：同步任务列表搜索-无搜索条件", "status": "passed", "attachments": [{"name": "请求方法：", "source": "1508349f-9b3b-4a9a-bef2-1bf875b086ac-attachment.attach"}, {"name": "请求地址", "source": "26e0ddfd-4033-4b86-b79b-1e9cf630a3be-attachment.attach"}, {"name": "请求头", "source": "9d81689f-5a24-4302-81f1-02b59bb5abd0-attachment.attach"}, {"name": "请求参数", "source": "518cdb59-a8d9-48d4-81cc-40e3e5caad27-attachment.attach"}, {"name": "请求结果", "source": "4add6fa3-87ae-4acf-bedf-91161f0ef446-attachment.attach"}], "start": 1687260109798, "stop": 1687260109877}, {"name": "结果校验", "status": "passed", "steps": [{"name": "状态码校验", "status": "passed", "attachments": [{"name": "期望状态码", "source": "11c6ae30-2429-45e6-af16-c9119716637e-attachment.attach"}, {"name": "实际状态码", "source": "180c7ab4-dc88-4fff-b762-63d1fd3cb40f-attachment.attach"}], "start": 1687260109877, "stop": 1687260109878}, {"name": "返回值校验", "status": "passed", "attachments": [{"name": "期望返回值", "source": "ed0ef63e-3ab0-45e5-9338-3001ebceb5f7-attachment.attach"}, {"name": "实际返回值", "source": "97effb29-03fd-4223-9482-5dbc365ffa3a-attachment.attach"}], "start": 1687260109878, "stop": 1687260109879}], "start": 1687260109877, "stop": 1687260109879}], "start": 1687260109771, "stop": 1687260109879}, {"name": "执行当前接口：获取同步根组id", "status": "passed", "attachments": [{"name": "请求方法：", "source": "011930c2-12d0-4bfd-8a65-5ad2b0cf435f-attachment.attach"}, {"name": "请求地址", "source": "1e28cd97-15ea-4330-b3da-041db86bbac6-attachment.attach"}, {"name": "请求头", "source": "08f99dff-842a-416c-88a6-a42396a9f801-attachment.attach"}, {"name": "请求参数", "source": "b98be57c-385c-4cad-8de3-b95fdaa5ecb5-attachment.attach"}, {"name": "请求结果", "source": "2a78e9d1-187c-4508-99e8-4bd237a21b90-attachment.attach"}], "start": 1687260109881, "stop": 1687260109946}, {"name": "结果校验", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 30, in check_result\n    assert_response(value, real_res)\n  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 45, in assert_response\n    assert flag\n"}, "steps": [{"name": "状态码校验", "status": "passed", "attachments": [{"name": "期望状态码", "source": "18297168-0f12-4972-ba33-71d7254b2c88-attachment.attach"}, {"name": "实际状态码", "source": "594e5e23-67ff-4e67-b4e1-aae8a049ad1d-attachment.attach"}], "start": 1687260109946, "stop": 1687260109946}, {"name": "返回值校验", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 45, in assert_response\n    assert flag\n"}, "attachments": [{"name": "期望返回值", "source": "35d622a2-a245-4a17-89a7-6d1117242344-attachment.attach"}, {"name": "实际返回值", "source": "3fecda1f-3830-40f9-8af0-66d4a8e4eb52-attachment.attach"}], "start": 1687260109946, "stop": 1687260109947}], "start": 1687260109946, "stop": 1687260109948}], "attachments": [{"name": "log", "source": "035b0526-29bc-4e1a-a2cc-ee7bd0902ec2-attachment.txt", "type": "text/plain"}], "start": 1687260109769, "stop": 1687260109948, "uuid": "9de7f144-2907-4d2a-86d8-2de935c72c93", "historyId": "c076d0bb657b7fadcb6dc7f1415a3243", "testCaseId": "8a41af8eca098c4295d5e872d129839c", "fullName": "bms.testcases.test_02_usersync.TestUserSync#test_usersync_get_syncgroupid", "labels": [{"name": "epic", "value": "用户管理"}, {"name": "feature", "value": "用户同步管理-用户同步"}, {"name": "story", "value": "编辑，获取同步根组id接口"}, {"name": "parentSuite", "value": "bms.testcases"}, {"name": "suite", "value": "test_02_usersync"}, {"name": "subSuite", "value": "TestUserSync"}, {"name": "host", "value": "OFYI7JX9DURTDV6"}, {"name": "thread", "value": "7756-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "bms.testcases.test_02_usersync"}]}