INFO     root:test_17_logbackup.py:55 ==========开始执行用例：logbackup_list_dbbackup_01==========
INFO     root:runcase.py:30 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 START-·-·-·-·-·-·-·-·-·-
INFO     root:handleyaml.py:94 Yaml测试用例基础架构检查通过
INFO     root:runcase.py:47 重组后的用例信息：{'name': '查询数据库所有备份信息-无筛选条件', 'description': '查询数据库所有备份信息-无筛选条件', 'request': {'data': {'nameDatabase': 'sas_v3_doc', 'pageNum': 1, 'pageSize': 20}, 'method': 'POST', 'address': '/api/auth/v1/log/queryBackupInfoByNameDatabase', 'headers': {'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6IjdlYTYwMzc0LTdjZTQtNGI0YS05ODNmLTYyMDNiZjQ1NTUxMSIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI3ZWE2MDM3NC03Y2U0LTRiNGEtOTgzZi02MjAzYmY0NTU1MTEiLCJleHAiOjE2ODc5NTMzMDUsImlhdCI6MTY4Nzc3MzMwNX0.ZEh_kobQplJq6Ir4jExaWcfxbJsVc9q3auT0UTeNUCqHMgPwJ8DcBIWCU3ymzQEDJAzxG6-6_IMLyGTayZfRDQ', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/syslogBackUp'}}, 'validate': {'code': 200, 'response': {'statusCode': 0, 'msg': 'success'}}, 'epic': '系统管理', 'feature': '运维管理-日志备份配置', 'story': '查询数据库所有备份信息接口', 'base_url': 'https://192.168.148.174:31000', 'caseid': 'logbackup_list_dbbackup_01'}
INFO     root:runcase.py:83 请求地址：https://192.168.148.174:31000/api/auth/v1/log/queryBackupInfoByNameDatabase
INFO     root:runcase.py:84 请求方法：POST
INFO     root:runcase.py:85 请求头：{'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6IjdlYTYwMzc0LTdjZTQtNGI0YS05ODNmLTYyMDNiZjQ1NTUxMSIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI3ZWE2MDM3NC03Y2U0LTRiNGEtOTgzZi02MjAzYmY0NTU1MTEiLCJleHAiOjE2ODc5NTMzMDUsImlhdCI6MTY4Nzc3MzMwNX0.ZEh_kobQplJq6Ir4jExaWcfxbJsVc9q3auT0UTeNUCqHMgPwJ8DcBIWCU3ymzQEDJAzxG6-6_IMLyGTayZfRDQ', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/syslogBackUp'}
INFO     root:runcase.py:95 请求参数：{'nameDatabase': 'sas_v3_doc', 'pageNum': 1, 'pageSize': 20}
DEBUG    urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): 192.168.148.174:31000
DEBUG    urllib3.connectionpool:connectionpool.py:456 https://192.168.148.174:31000 "POST /api/auth/v1/log/queryBackupInfoByNameDatabase HTTP/1.1" 200 527
INFO     root:runcase.py:157 请求接口结果： {'statusCode': 0, 'msg': 'success', 'data': {'totalCount': 2, 'list': [{'id': 1, 'savePath': '/BackupData', 'realPath': '/home/docker/volumes/esBackupData/_data', 'uploadFtpState': '上传ftp成功', 'nameDatabase': 'sas_v3_doc', 'saveTime': '2023-06-25 17:29:22', 'fileName': '2023-06-25_17_29_22-sas_v3_doc.csv'}, {'id': 2, 'savePath': '/BackupData', 'realPath': '/home/docker/volumes/esBackupData/_data', 'uploadFtpState': '上传ftp成功', 'nameDatabase': 'sas_v3_doc', 'saveTime': '2023-06-25 17:29:35', 'fileName': '2023-06-25_17_29_34-sas_v3_doc.csv'}]}}
INFO     root:checkresult.py:113 code断言通过, 期望状态码:200, 实际状态码:200
INFO     root:checkresult.py:48 返回结果断言通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 0, 'msg': 'success', 'data': {'totalCount': 2, 'list': [{'id': 1, 'savePath': '/BackupData', 'realPath': '/home/docker/volumes/esBackupData/_data', 'uploadFtpState': '上传ftp成功', 'nameDatabase': 'sas_v3_doc', 'saveTime': '2023-06-25 17:29:22', 'fileName': '2023-06-25_17_29_22-sas_v3_doc.csv'}, {'id': 2, 'savePath': '/BackupData', 'realPath': '/home/docker/volumes/esBackupData/_data', 'uploadFtpState': '上传ftp成功', 'nameDatabase': 'sas_v3_doc', 'saveTime': '2023-06-25 17:29:35', 'fileName': '2023-06-25_17_29_34-sas_v3_doc.csv'}]}}
INFO     root:runcase.py:63 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 END-·-·-·-·-·-·-·-·-·-